/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MaterialPerformanceRouteImport } from './routes/material-performance'
import { Route as GmvAttributionAdminRouteImport } from './routes/gmv-attribution-admin'
import { Route as GmvAttributionRouteImport } from './routes/gmv-attribution'
import { Route as FeishuDataRouteImport } from './routes/feishu-data'
import { Route as CommentsRouteImport } from './routes/comments'
import { Route as ApiTestRouteImport } from './routes/api-test'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthTiktokCallbackRouteImport } from './routes/oauth.tiktok.callback'
import { Route as ApiPublicHooksGmvMaxCronRouteImport } from './routes/api/public/hooks/gmv-max-cron'
import { Route as ApiPublicHooksAuthorizeCronRouteImport } from './routes/api/public/hooks/authorize-cron'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialPerformanceRoute = MaterialPerformanceRouteImport.update({
  id: '/material-performance',
  path: '/material-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const GmvAttributionAdminRoute = GmvAttributionAdminRouteImport.update({
  id: '/gmv-attribution-admin',
  path: '/gmv-attribution-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const GmvAttributionRoute = GmvAttributionRouteImport.update({
  id: '/gmv-attribution',
  path: '/gmv-attribution',
  getParentRoute: () => rootRouteImport,
} as any)
const FeishuDataRoute = FeishuDataRouteImport.update({
  id: '/feishu-data',
  path: '/feishu-data',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRoute = CommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRoute = ApiTestRouteImport.update({
  id: '/api-test',
  path: '/api-test',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthTiktokCallbackRoute = OauthTiktokCallbackRouteImport.update({
  id: '/oauth/tiktok/callback',
  path: '/oauth/tiktok/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksGmvMaxCronRoute =
  ApiPublicHooksGmvMaxCronRouteImport.update({
    id: '/api/public/hooks/gmv-max-cron',
    path: '/api/public/hooks/gmv-max-cron',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAuthorizeCronRoute =
  ApiPublicHooksAuthorizeCronRouteImport.update({
    id: '/api/public/hooks/authorize-cron',
    path: '/api/public/hooks/authorize-cron',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-test': typeof ApiTestRoute
  '/comments': typeof CommentsRoute
  '/feishu-data': typeof FeishuDataRoute
  '/gmv-attribution': typeof GmvAttributionRoute
  '/gmv-attribution-admin': typeof GmvAttributionAdminRoute
  '/material-performance': typeof MaterialPerformanceRoute
  '/settings': typeof SettingsRoute
  '/oauth/tiktok/callback': typeof OauthTiktokCallbackRoute
  '/api/public/hooks/authorize-cron': typeof ApiPublicHooksAuthorizeCronRoute
  '/api/public/hooks/gmv-max-cron': typeof ApiPublicHooksGmvMaxCronRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-test': typeof ApiTestRoute
  '/comments': typeof CommentsRoute
  '/feishu-data': typeof FeishuDataRoute
  '/gmv-attribution': typeof GmvAttributionRoute
  '/gmv-attribution-admin': typeof GmvAttributionAdminRoute
  '/material-performance': typeof MaterialPerformanceRoute
  '/settings': typeof SettingsRoute
  '/oauth/tiktok/callback': typeof OauthTiktokCallbackRoute
  '/api/public/hooks/authorize-cron': typeof ApiPublicHooksAuthorizeCronRoute
  '/api/public/hooks/gmv-max-cron': typeof ApiPublicHooksGmvMaxCronRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-test': typeof ApiTestRoute
  '/comments': typeof CommentsRoute
  '/feishu-data': typeof FeishuDataRoute
  '/gmv-attribution': typeof GmvAttributionRoute
  '/gmv-attribution-admin': typeof GmvAttributionAdminRoute
  '/material-performance': typeof MaterialPerformanceRoute
  '/settings': typeof SettingsRoute
  '/oauth/tiktok/callback': typeof OauthTiktokCallbackRoute
  '/api/public/hooks/authorize-cron': typeof ApiPublicHooksAuthorizeCronRoute
  '/api/public/hooks/gmv-max-cron': typeof ApiPublicHooksGmvMaxCronRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-test'
    | '/comments'
    | '/feishu-data'
    | '/gmv-attribution'
    | '/gmv-attribution-admin'
    | '/material-performance'
    | '/settings'
    | '/oauth/tiktok/callback'
    | '/api/public/hooks/authorize-cron'
    | '/api/public/hooks/gmv-max-cron'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-test'
    | '/comments'
    | '/feishu-data'
    | '/gmv-attribution'
    | '/gmv-attribution-admin'
    | '/material-performance'
    | '/settings'
    | '/oauth/tiktok/callback'
    | '/api/public/hooks/authorize-cron'
    | '/api/public/hooks/gmv-max-cron'
  id:
    | '__root__'
    | '/'
    | '/api-test'
    | '/comments'
    | '/feishu-data'
    | '/gmv-attribution'
    | '/gmv-attribution-admin'
    | '/material-performance'
    | '/settings'
    | '/oauth/tiktok/callback'
    | '/api/public/hooks/authorize-cron'
    | '/api/public/hooks/gmv-max-cron'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTestRoute: typeof ApiTestRoute
  CommentsRoute: typeof CommentsRoute
  FeishuDataRoute: typeof FeishuDataRoute
  GmvAttributionRoute: typeof GmvAttributionRoute
  GmvAttributionAdminRoute: typeof GmvAttributionAdminRoute
  MaterialPerformanceRoute: typeof MaterialPerformanceRoute
  SettingsRoute: typeof SettingsRoute
  OauthTiktokCallbackRoute: typeof OauthTiktokCallbackRoute
  ApiPublicHooksAuthorizeCronRoute: typeof ApiPublicHooksAuthorizeCronRoute
  ApiPublicHooksGmvMaxCronRoute: typeof ApiPublicHooksGmvMaxCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-performance': {
      id: '/material-performance'
      path: '/material-performance'
      fullPath: '/material-performance'
      preLoaderRoute: typeof MaterialPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gmv-attribution-admin': {
      id: '/gmv-attribution-admin'
      path: '/gmv-attribution-admin'
      fullPath: '/gmv-attribution-admin'
      preLoaderRoute: typeof GmvAttributionAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gmv-attribution': {
      id: '/gmv-attribution'
      path: '/gmv-attribution'
      fullPath: '/gmv-attribution'
      preLoaderRoute: typeof GmvAttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feishu-data': {
      id: '/feishu-data'
      path: '/feishu-data'
      fullPath: '/feishu-data'
      preLoaderRoute: typeof FeishuDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-test': {
      id: '/api-test'
      path: '/api-test'
      fullPath: '/api-test'
      preLoaderRoute: typeof ApiTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/tiktok/callback': {
      id: '/oauth/tiktok/callback'
      path: '/oauth/tiktok/callback'
      fullPath: '/oauth/tiktok/callback'
      preLoaderRoute: typeof OauthTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/gmv-max-cron': {
      id: '/api/public/hooks/gmv-max-cron'
      path: '/api/public/hooks/gmv-max-cron'
      fullPath: '/api/public/hooks/gmv-max-cron'
      preLoaderRoute: typeof ApiPublicHooksGmvMaxCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/authorize-cron': {
      id: '/api/public/hooks/authorize-cron'
      path: '/api/public/hooks/authorize-cron'
      fullPath: '/api/public/hooks/authorize-cron'
      preLoaderRoute: typeof ApiPublicHooksAuthorizeCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTestRoute: ApiTestRoute,
  CommentsRoute: CommentsRoute,
  FeishuDataRoute: FeishuDataRoute,
  GmvAttributionRoute: GmvAttributionRoute,
  GmvAttributionAdminRoute: GmvAttributionAdminRoute,
  MaterialPerformanceRoute: MaterialPerformanceRoute,
  SettingsRoute: SettingsRoute,
  OauthTiktokCallbackRoute: OauthTiktokCallbackRoute,
  ApiPublicHooksAuthorizeCronRoute: ApiPublicHooksAuthorizeCronRoute,
  ApiPublicHooksGmvMaxCronRoute: ApiPublicHooksGmvMaxCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
