/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MaterialPerformanceRouteImport } from './routes/material-performance'
import { Route as CommentsRouteImport } from './routes/comments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthTiktokCallbackRouteImport } from './routes/oauth.tiktok.callback'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialPerformanceRoute = MaterialPerformanceRouteImport.update({
  id: '/material-performance',
  path: '/material-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentsRoute = CommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthTiktokCallbackRoute = OauthTiktokCallbackRouteImport.update({
  id: '/oauth/tiktok/callback',
  path: '/oauth/tiktok/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comments': typeof CommentsRoute
  '/material-performance': typeof MaterialPerformanceRoute
  '/settings': typeof SettingsRoute
  '/oauth/tiktok/callback': typeof OauthTiktokCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comments': typeof CommentsRoute
  '/material-performance': typeof MaterialPerformanceRoute
  '/settings': typeof SettingsRoute
  '/oauth/tiktok/callback': typeof OauthTiktokCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comments': typeof CommentsRoute
  '/material-performance': typeof MaterialPerformanceRoute
  '/settings': typeof SettingsRoute
  '/oauth/tiktok/callback': typeof OauthTiktokCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comments'
    | '/material-performance'
    | '/settings'
    | '/oauth/tiktok/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comments'
    | '/material-performance'
    | '/settings'
    | '/oauth/tiktok/callback'
  id:
    | '__root__'
    | '/'
    | '/comments'
    | '/material-performance'
    | '/settings'
    | '/oauth/tiktok/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommentsRoute: typeof CommentsRoute
  MaterialPerformanceRoute: typeof MaterialPerformanceRoute
  SettingsRoute: typeof SettingsRoute
  OauthTiktokCallbackRoute: typeof OauthTiktokCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-performance': {
      id: '/material-performance'
      path: '/material-performance'
      fullPath: '/material-performance'
      preLoaderRoute: typeof MaterialPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comments': {
      id: '/comments'
      path: '/comments'
      fullPath: '/comments'
      preLoaderRoute: typeof CommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/tiktok/callback': {
      id: '/oauth/tiktok/callback'
      path: '/oauth/tiktok/callback'
      fullPath: '/oauth/tiktok/callback'
      preLoaderRoute: typeof OauthTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommentsRoute: CommentsRoute,
  MaterialPerformanceRoute: MaterialPerformanceRoute,
  SettingsRoute: SettingsRoute,
  OauthTiktokCallbackRoute: OauthTiktokCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
